### PR TITLE
add feature to create geometries on grid

### PR DESCRIPTION
**Pull request by Licini**
prototyping the feature to add objects on grid /xy plane. It's done through painting a uv plane at same extent of the grid object. where the red and green channel represent the u and v coords of the plane. a snap_to_grid option is also provided by rounding up with the grid cell size.

Question: should we allow the click-able area extend outside of the grid?

### CODE REVIEW

**Comment by brgcode** [comment]
> Question: should we allow the click-able area extend outside of the grid?

not sure. what do you think?

**Comment by Licini** [comment]
I think its a bit more manageable to keep grid and plane to the same range, both visually and conceptually.
So when we need a larger selectable range, we just increase the size of grid.

**Comment by brgcode** [comment]
okay sounds good.
ready to merge?

**Comment by Licini** [comment]
Yep ready

**Pull request merged**
