### PR TITLE
add collection and collection object

### PR DESCRIPTION
**Pull request by Licini**
Separate PR for Collection

### CODE REVIEW

**Comment by Licini** [comment]
Not ready yet!

**Comment by brgcode** [comment]
> Not ready yet!

ok!

**Comment by brgcode** [comment]
noticed again that things are slow if you draw many individual shapes. would be good to get this to work. and hopefully it makes a difference :) but i guess we should in any case try to switch to one big buffer when possible...

**Comment by Licini** [comment]
> noticed again that things are slow if you draw many individual shapes. would be good to get this to work. and hopefully it makes a difference :) but i guess we should in any case try to switch to one big buffer when possible...

I think it's ready now

**Comment by brgcode** [comment]
could you merge in main to resolve conflicts?

**Comment by Licini** [comment]
> could you merge in main to resolve conflicts?

Sure, done

**Pull request merged**
