### PR TITLE
docs-only

### PR DESCRIPTION
**Pull request by Licini**
For the ancient issue of #16

### CODE REVIEW

**Comment by Licini** [comment]
It ends up a bit complicated than thought, since it's a bit tricky to get the commit message from a pull request. So a `pre-ci` job is added for this purpose. 

So now any commits that contain the string `[docs-only]` will be skipped building. 
An example commit can be `git commit -m "updated tutorials for abc [docs-only]"`

**Comment by brgcode** [comment]
and this cant be handled with a label?

**Comment by Licini** [comment]
> and this cant be handled with a label?

Do you mean a tag? Was my first thought too. But the problem is that pushing of a tag and commit are treated as two separate events. The the building job will still be trigger if you accompany a commit with a tag

**Comment by Licini** [comment]
> > and this cant be handled with a label?
> 
> Do you mean a tag? Was my first thought too. But the problem is that pushing of a tag and commit are treated as two separate events. The the building job will still be trigger if you accompany a commit with a tag

or Do you mean by assigning a label in the pull request?

**Comment by brgcode** [comment]
assigning a label to the PR

**Comment by Licini** [comment]
> assigning a label to the PR
😂 That's a good point, I somehow misunderstood it in the beginning

**Comment by Licini** [comment]
@brgcode it works with label, now it's just one-line difference, much cleaner.

**Comment by brgcode** [comment]
cool!

**Pull request merged**
